//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishesmenu
    {
        public int Id { get; set; }
        public Nullable<int> idDishes { get; set; }
        public string Name { get; set; }
        public Nullable<int> Ves { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> idMenu { get; set; }
        public string Category { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
