//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataKursEntities5 : DbContext
    {
        public DataKursEntities5()
            : base("name=DataKursEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Dishesmenu> Dishesmenu { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
    }
}
